backend:
  name: git-gateway # Link the CMS with a Git repo via Netlify
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img # Store uploaded images in this folder
public_folder: /img # Where to find the images in the live site
collections:
  - name: "songs" # Used in routes, e.g. admin/collections/work
    label: "Song" # Used in the CMS UI
    folder: "src/data/songs" # Where the files will be stored
    create: true # Users can create new posts
    slug: "{{slug}}" # Creates a safe slug from the post's title, which will be used for the post's filename
    fields: # The fields for each document
      - { label: "Song No.", name: "songno", widget: "number" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Tags", name: "tags", widget: "string" }
      - { label: "Content", name: "content", widget: "markdown" }
      - { label: "About", name: "about", widget: "text" }
  - name: "verses" # Used in routes, e.g. admin/collections/work
    label: "Verse" # Used in the CMS UI
    folder: "src/data/verses" # Where the files will be stored
    create: true # Users can create new posts
    slug: "{{slug}}" # Creates a safe slug from the post's title, which will be used for the post's filename
    fields: # The fields for each document
      - { label: "Title (Refernce)", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "string" }
      - { label: "Content", name: "content", widget: "markdown" }
